In [2]:
 import numpy as np

## steps
* basic array creation 

#  LIST V/S ARRAY

* ARRAY DOESNT SUPPORT HETROGENOUS DATA BUT LIST CAN.
* array store same data type but list store all type
* array are memory efficient but list are not
* ARRAY CAN BE MULTI-DIMENTIONAL  BUT LIST CANT.

In [125]:
arr=np.array([1,2,3,4])
# print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

In [126]:
a=[1,2,3.5,4]
print(a)
# a

[1, 2, 3.5, 4]


In [5]:
np.array(a)

array([1. , 2. , 3.5, 4. ])

In [6]:
L=[[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr1=np.array(L)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arange ---> x=np.arange(start:end+1:skip)

In [11]:
arange1=np.arange(1,11)
arange1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arange1=np.arange(1,11,2)
arange1

array([1, 3, 5, 7, 9])

#  ZEROES / ONES  ---> 
* y=np.zeroes/ones((rows,columns))

* y=np.zeroes/ones(columns)

In [14]:
arr0=np.zeros((4,8))
arr0

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
arr0=np.ones((4,8))
arr0

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

# Linspace->LinearSpace
### ye 2 number k bich m equal differance k number ko data h jo ki  jisme 3 arguments hote h 


*  lin= np.linspace(start,end,no. of numbers required in between)


In [19]:
lin= np.linspace(1,5,5)
lin

array([1., 2., 3., 4., 5.])

In [26]:
lin= np.linspace(1,5,10,retstep=True)
lin

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [21]:
lin= np.linspace(1,5,4)
lin

array([1.        , 2.33333333, 3.66666667, 5.        ])

#  Random  Generation Function 

* Rand ---->  rand1=np.random.rand(num)---> it generates randomly 10 numbers between 0 and 1


*  Randn---> randn1=np.random.randn(num) ---> it generates random number in between the range of  3 to +3 as it is random normal form where mean=0 and sd=1


* Randint1----->randint1=np.random.randint(num)---> grnerates random number between 0 to num. ---> generates only one  random number

#### randint1=np.random.randint(low_num,High_num, no. of numbers required in between high and low)

In [3]:
rand1=np.random.rand(19)
rand1

array([0.34178694, 0.41011324, 0.18879331, 0.07829511, 0.05149039,
       0.72051326, 0.63454706, 0.52958045, 0.38035312, 0.07748729,
       0.15041702, 0.17266648, 0.81161042, 0.03279716, 0.76372371,
       0.38264565, 0.97284649, 0.47468954, 0.98059771])

In [34]:
randn1=np.random.randn(10)
randn1

array([ 1.26611874, -1.71778405,  2.25449662, -0.4645919 ,  2.19617134,
        0.17980449, -2.1444392 ,  2.19244688,  0.39639877,  0.71354004])

In [7]:
randint1=np.random.randint(10)
randint1

7

In [9]:
randint1=np.random.randint(10,20,10)
randint1

array([12, 16, 11, 11, 18, 15, 16, 10, 11, 18])

# Array Attributes 

In [41]:
arratt=np.array([[1,2,3],[4,5,6],[7,8,9]])
arratt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arratt.shape

(3, 3)

In [43]:
arratt.size

9

In [44]:
arratt.dtype

dtype('int32')

In [45]:
arratt.min()

1

In [46]:
arratt.max()

9

In [47]:
arratt.sum()

45

In [54]:
np.sum(arratt,axis=0)   # sums the col1, col2 ,col3

array([12, 15, 18])

In [55]:
np.sum(arratt,axis=1)

array([ 6, 15, 24])

In [56]:
arratt.mean()

5.0

In [57]:
arratt.std()


2.581988897471611

In [58]:
arratt.argmin()

0

In [59]:
arratt.argmax()

8


#  Reshaping and Resizing 

In [61]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [63]:
arr.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

# Array indexing and slicing of vectors --->
* vector    [ ]
* matrix    [ [ ] ]

In [66]:
arr1=np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [67]:
arr1[6]

17

In [69]:
arr1[1:5]   #same as list slicing

array([12, 13, 14, 15])

# Array indexing and slicing of matrix

In [74]:
arr2=np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [79]:
arr2[0]  # identification of single  row 

array([1, 2, 3, 4, 5])

In [80]:
arr2[1,3]   # identify the specific element in rows and columns

9

In [85]:
# slice=arr2[row:row,col:col]

slice=arr2[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [86]:
slice1=arr2[3: ,3:]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

# Boolean indexing 

In [87]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
bool_even=arr%2==0
bool_even

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [90]:
arr=arr[bool_even]
arr

array([12, 14, 16, 18, 20])

# ARRAY OPERATIONS

### ARITHMATIC OPERATIONS

In [91]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [92]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [93]:
a1-a2

array([-5, -5, -5, -5, -5])

In [94]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [95]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [97]:
a1//a2   #floor division  isme 1/6~0

array([0, 0, 0, 0, 0])

In [98]:
a1**a2  # expo   isme 1^6,2^7,....

array([      1,     128,    6561,  262144, 9765625])

In [103]:
# broadcasting

l=[10,20,30]
arr7=np.array(l)
arr

array([10, 20, 30])

In [105]:
arr7 + 10


array([20, 30, 40])

### matrix multiplication

In [107]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [108]:
A

array([[1, 2],
       [3, 4]])

In [109]:
B

array([[5, 6],
       [7, 8]])

In [110]:
A @ B    # matrix dot product multiplication

array([[19, 22],
       [43, 50]])

In [111]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [112]:
# transpose row into column

A.T

array([[1, 3],
       [2, 4]])

# advance array manipulation  

#### stacking array--->ye sirf vector m possible h matrix m nhi hota h

In [113]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [114]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [115]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [118]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### array spliting

In [119]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [120]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [121]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [122]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [123]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [152]:

 
# Valid Sudoku

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
# General Questions

import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
#Get the shape of the matrix.
#Find the average age of students.
#Extract Math marks of all students.
#Find the highest Science mark.
#Get details of the student who scored more than 90 in Math.
#Increase Math marks of all students by 5.
#Find how many students are younger than 19.
#Calculate the average marks in each subject (column-wise mean).
#Get data of students who scored at least 80 in both subjects.
#Replace all Science marks < 75 with 0.

In [153]:
#Get details of the student who scored more than 90 in Maths.
# data[:,1]>90
data[data[:,1]>90]

array([[19, 92, 88]])

In [154]:
#Find the highest Science mark.
data[:,2].max()


95

In [155]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [156]:
#Replace all Science marks < 75 with 0.

# data[:,2]

In [157]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [158]:
#Find the average age of students.
age_avg=data[:,0]
age_avg.mean()

18.4

In [159]:
#Extract Math marks of all students.

data[:,1]

array([85, 92, 76, 65, 90])